# D659/.github/workflows/call-reusable-workflow.yml
name: Call Reusable Export Coda Document to Markdown

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: List files in repository
        run: ls -l ${{ github.workspace }}

      - name: Call reusable workflow
        uses: wgu-programs/coda-export/.github/workflows/export-coda-markdown.yml@main
        with:
          docID: '_d1s_ZG0bmZ4'
        secrets:
          CODA_API_KEY: ${{ secrets.CODA_API_KEY }}
