name: Call Reusable Export Coda Document to Markdown

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: wgu-programs/coda-export/.github/workflows/export-coda-markdown.yml@main
    with:
      docID: ${{ vars.CODA_DOC_ID }}
    secrets:
      CODA_API_KEY: ${{ secrets.CODA_API_KEY }}
